### ISSUE TITLE
Random error when calling JenkinsJobConfiguraPage.setRePromoteValue

### ISSUE THREAD

**Issue by petod108** [opendevstack/ods-e2e-tests#18]
Random error while calling **JenkinsJobConfiguraPage.setRePromoteValue**

`geb.error.RequiredPageContentNotPresent: The required page content 'org.ods.e2e.jenkins.pages.JenkinsJobConfigurePage -> paramsTable: geb.navigator.DefaultNavigator' is not present`
**Stacktrace:**
geb.error.RequiredPageContentNotPresent: The required page content 'org.ods.e2e.jenkins.pages.JenkinsJobConfigurePage -> paramsTable: geb.navigator.DefaultNavigator' is not present
	at geb.content.TemplateDerivedPageContent.require(TemplateDerivedPageContent.groovy:64)
	at geb.content.PageContentTemplate.create_closure1(PageContentTemplate.groovy:63)
	at geb.content.PageContentTemplate.create_closure1(PageContentTemplate.groovy)
	at geb.content.PageContentTemplate.create(PageContentTemplate.groovy:87)
	at geb.content.PageContentTemplate.get(PageContentTemplate.groovy:54)
	at geb.content.DefaultPageContentSupport.getContent(DefaultPageContentSupport.groovy:42)
	at geb.content.PageContentSupport.propertyMissing(PageContentSupport.groovy:41)
	at geb.Page.propertyMissing(Page.groovy:110)
	at org.ods.e2e.jenkins.pages.JenkinsJobConfigurePage.existParam(JenkinsJobConfigurePage.groovy:30)
	at org.ods.e2e.jenkins.pages.JenkinsJobConfigurePage.setParameterValue(JenkinsJobConfigurePage.groovy:41)
	at org.ods.e2e.jenkins.pages.JenkinsJobConfigurePage.setRePromoteValue(JenkinsJobConfigurePage.groovy:68)

![001-002-RT_08_001-end](https://user-images.githubusercontent.com/9747012/124632279-7ed6fc80-de84-11eb-9266-78ff5f693d68.png)

**Comment by metmajer** [comment]
@petod108 what is the scope of the test? Are you trying to manipulate Jenkins settings? `org.ods.e2e.jenkins.pages` shows that the issue is in a package that we own (good). Have you tried working with a timeout or an event-based approach to ensure an element that gets rendered after the page load event is present before you reference it?

FYI @jorge-romero @s2oBCN @clemensutschig
